// Gjeneruar automatikisht nga katalogu origjinal KRIEL / Caggiati.
export type SeedCategory = { id: string; name: string; sort: number };
export type SeedProduct = { id: string; categoryId: string; name: string; code: string; price: number; dims: string; mat: string; img: string; featured: boolean; featuredOrder: number };

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    "id": "germa",
    "name": "Gërma Bronzi",
    "sort": 1
  },
  {
    "id": "korniza",
    "name": "Korniza Bronzi",
    "sort": 2
  },
  {
    "id": "kryqe",
    "name": "Kryqe Bronzi",
    "sort": 3
  },
  {
    "id": "lule",
    "name": "Lule Bronzi",
    "sort": 4
  },
  {
    "id": "llampa",
    "name": "Llampa & Qirinj",
    "sort": 5
  },
  {
    "id": "vazo",
    "name": "Vazo & Urna",
    "sort": 6
  },
  {
    "id": "statuja",
    "name": "Statuja Bronzi",
    "sort": 7
  },
  {
    "id": "targa",
    "name": "Targa & Bazoreliev",
    "sort": 8
  },
  {
    "id": "mozaik",
    "name": "Mozaik Qelqi",
    "sort": 9
  },
  {
    "id": "ndricim",
    "name": "Drita & Porselan",
    "sort": 10
  }
];

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    "id": "statue-35-264_61",
    "categoryId": "statuja",
    "name": "Madonna me duar të bashkuara",
    "code": "COD. 35 264/61",
    "price": 402.9,
    "dims": "Lartësia 63 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": true,
    "featuredOrder": 1
  },
  {
    "id": "statue-35-082_26",
    "categoryId": "statuja",
    "name": "Madonna në lutje",
    "code": "COD. 35 082/26",
    "price": 210.9,
    "dims": "Lartësia 26 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-581_28",
    "categoryId": "statuja",
    "name": "Madonna me mantil të artë",
    "code": "COD. 35 581/28",
    "price": 220.9,
    "dims": "Lartësia 28 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-223_74",
    "categoryId": "statuja",
    "name": "Madonna e Kujtesës",
    "code": "COD. 35 223/74",
    "price": 465.9,
    "dims": "Lartësia 75 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-300_65",
    "categoryId": "statuja",
    "name": "Madonna me lule",
    "code": "COD. 35 300/65",
    "price": 413.9,
    "dims": "Lartësia 65 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-37-180_87",
    "categoryId": "statuja",
    "name": "Pietà e ulur",
    "code": "COD. 37 180/87",
    "price": 527.9,
    "dims": "Lartësia 87 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-110_41",
    "categoryId": "statuja",
    "name": "Vajza me vazo lulesh",
    "code": "COD. 35 110/41",
    "price": 288.9,
    "dims": "Lartësia 41 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-37-210_67",
    "categoryId": "statuja",
    "name": "Vajza me shportë lulesh",
    "code": "COD. 37 210/67",
    "price": 423.9,
    "dims": "Lartësia 67 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-37-061_80",
    "categoryId": "statuja",
    "name": "Vajza me lule në dorë",
    "code": "COD. 37 061/80",
    "price": 491.9,
    "dims": "Lartësia 80 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-047_39",
    "categoryId": "statuja",
    "name": "Madonna moderne",
    "code": "COD. 35 047/39",
    "price": 277.9,
    "dims": "Lartësia 39 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-36-881_44",
    "categoryId": "statuja",
    "name": "Krishti i Ringjallur",
    "code": "COD. 36 881/44",
    "price": 303.9,
    "dims": "Lartësia 44 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-37-690_101",
    "categoryId": "statuja",
    "name": "Krishti duke mbartur Kryqin",
    "code": "COD. 37 690/101",
    "price": 257.9,
    "dims": "Lartësia 35 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-37-990_89",
    "categoryId": "statuja",
    "name": "Krishti në përuletje",
    "code": "COD. 37 990/89",
    "price": 293.9,
    "dims": "Lartësia 42 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "statue-35-003_60",
    "categoryId": "statuja",
    "name": "Madonna — bronz",
    "code": "COD. 35 003/60",
    "price": 387.9,
    "dims": "Lartësia 60 cm",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/statuja.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-533_20",
    "categoryId": "kryqe",
    "name": "Kryq modern i errët",
    "code": "COD. 23 533/20",
    "price": 47.9,
    "dims": "Lartësia 16 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": true,
    "featuredOrder": 2
  },
  {
    "id": "kryqe-23-040_40",
    "categoryId": "kryqe",
    "name": "Kryq i artë trekëndor",
    "code": "COD. 23 040/40",
    "price": 73.9,
    "dims": "Lartësia 35 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-017_20",
    "categoryId": "kryqe",
    "name": "Kryq i hollë i artë",
    "code": "COD. 23 017/20",
    "price": 46.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-010_20",
    "categoryId": "kryqe",
    "name": "Kryq klasik i artë",
    "code": "COD. 23 010/20",
    "price": 44.9,
    "dims": "Lartësia 14 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-118_40",
    "categoryId": "kryqe",
    "name": "Kryq i artë me gdhendje",
    "code": "COD. 23 118/40",
    "price": 66.9,
    "dims": "Lartësia 30 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-22-053_65",
    "categoryId": "kryqe",
    "name": "Mbishkrimi INRI në bronz",
    "code": "COD. 22 053/65",
    "price": 43.9,
    "dims": "Lartësia 13 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-24-830_20",
    "categoryId": "kryqe",
    "name": "Kryq me kristal dielli",
    "code": "COD. 24 830/20",
    "price": 53.9,
    "dims": "Lartësia 20 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-24-830_20-b",
    "categoryId": "kryqe",
    "name": "Kryq Ortodoks",
    "code": "COD. 24 830/20",
    "price": 42.9,
    "dims": "Lartësia 12 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-311_20",
    "categoryId": "kryqe",
    "name": "Kryq rustik modern",
    "code": "COD. 23 311/20",
    "price": 46.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-098_10",
    "categoryId": "kryqe",
    "name": "Kryq me teksturë litare",
    "code": "COD. 23 098/10",
    "price": 50.9,
    "dims": "Lartësia 18 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-003_40",
    "categoryId": "kryqe",
    "name": "Kryq me fije të arta",
    "code": "COD. 23 003/40",
    "price": 80.9,
    "dims": "Lartësia 40 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-050_20",
    "categoryId": "kryqe",
    "name": "Kryqëzim klasik me Krishtin",
    "code": "COD. 23 050/20",
    "price": 46.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-24-168_40",
    "categoryId": "kryqe",
    "name": "Kryqëzim me zinxhir trëndafili",
    "code": "COD. 24 168/40",
    "price": 80.9,
    "dims": "Lartësia 40 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-23-896_40",
    "categoryId": "kryqe",
    "name": "Kryqëzim me trëndafil të kuq",
    "code": "COD. 23 896/40",
    "price": 80.9,
    "dims": "Lartësia 40 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "kryqe-24-185_20",
    "categoryId": "kryqe",
    "name": "Kryqëzim me degë trëndafili",
    "code": "COD. 24 185/20",
    "price": 46.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 — patinë / finish i artë",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-681_53",
    "categoryId": "lule",
    "name": "Luledielli Bronzi",
    "code": "COD. 29 681/53",
    "price": 80.9,
    "dims": "Lartësia 53 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-693_51",
    "categoryId": "lule",
    "name": "Trëndafil me kërcell të gjatë",
    "code": "COD. 29 693/51",
    "price": 78.9,
    "dims": "Lartësia 51 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-124_14",
    "categoryId": "lule",
    "name": "Trëndafil i artë",
    "code": "COD. 29 124/14",
    "price": 36.9,
    "dims": "Lartësia 14 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-539_24",
    "categoryId": "lule",
    "name": "Tulipan Bronzi",
    "code": "COD. 29 539/24",
    "price": 47.9,
    "dims": "Lartësia 24 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-260_13",
    "categoryId": "lule",
    "name": "Trëndafil me gjethe",
    "code": "COD. 29 260/13",
    "price": 34.9,
    "dims": "Lartësia 13 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-270_18",
    "categoryId": "lule",
    "name": "Trëndafil i kuq",
    "code": "COD. 29 270/18",
    "price": 40.9,
    "dims": "Lartësia 18 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-596_23",
    "categoryId": "lule",
    "name": "Herdhe e artë (Edera)",
    "code": "COD. 29 596/23",
    "price": 46.9,
    "dims": "Lartësia 23 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-506_25",
    "categoryId": "lule",
    "name": "Lule pjeshke",
    "code": "COD. 29 506/25",
    "price": 48.9,
    "dims": "Lartësia 25 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-483_16",
    "categoryId": "lule",
    "name": "Vjollca e vogël",
    "code": "COD. 29 483/16",
    "price": 38.9,
    "dims": "Lartësia 16 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-404_23",
    "categoryId": "lule",
    "name": "Zambak (Giglio)",
    "code": "COD. 29 404/23",
    "price": 46.9,
    "dims": "Lartësia 23 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-415_20",
    "categoryId": "lule",
    "name": "Yll i Alpove",
    "code": "COD. 29 415/20",
    "price": 43.9,
    "dims": "Lartësia 20 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-585_22",
    "categoryId": "lule",
    "name": "Kalli i grurit (Spiga)",
    "code": "COD. 29 585/22",
    "price": 45.9,
    "dims": "Lartësia 22 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-541_21",
    "categoryId": "lule",
    "name": "Syth trëndafili",
    "code": "COD. 29 541/21",
    "price": 44.9,
    "dims": "Lartësia 21 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-31-085_13",
    "categoryId": "lule",
    "name": "Duart me Trëndafil",
    "code": "COD. 31 085/13",
    "price": 34.9,
    "dims": "Lartësia 13 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-058_27",
    "categoryId": "lule",
    "name": "Kala e bardhë",
    "code": "COD. 29 058/27",
    "price": 51.9,
    "dims": "Lartësia 27 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "lule-29-024_42",
    "categoryId": "lule",
    "name": "Kala (Zantedeschia)",
    "code": "COD. 29 024/42",
    "price": 68.9,
    "dims": "Lartësia 42 cm",
    "mat": "Bronz 87 i punuar dorë",
    "img": "/images/categories/lule.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-180_19",
    "categoryId": "llampa",
    "name": "Llambë qiriu me gjethe",
    "code": "COD. 10 180/19",
    "price": 137.9,
    "dims": "Lartësia 19 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": true,
    "featuredOrder": 3
  },
  {
    "id": "llampa-10-135_20",
    "categoryId": "llampa",
    "name": "Llambë klasike ovale",
    "code": "COD. 10 135/20",
    "price": 140.9,
    "dims": "Lartësia 20 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-016_20",
    "categoryId": "llampa",
    "name": "Llambë e gjelbër klasike",
    "code": "COD. 10 016/20",
    "price": 140.9,
    "dims": "Lartësia 20 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-48",
    "categoryId": "llampa",
    "name": "Llambë moderne katrore",
    "code": "",
    "price": 147.9,
    "dims": "Lartësia 23 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-11-904_24",
    "categoryId": "llampa",
    "name": "Llambë fener klasike",
    "code": "COD. 11 904/24",
    "price": 154.9,
    "dims": "Lartësia 26 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-933_18",
    "categoryId": "llampa",
    "name": "Llambë ovale moderne",
    "code": "COD. 10 933/18",
    "price": 135.9,
    "dims": "Lartësia 18 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-721_16",
    "categoryId": "llampa",
    "name": "Llambë fener me kryq",
    "code": "COD. 10 721/16",
    "price": 128.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-492_19",
    "categoryId": "llampa",
    "name": "Llambë me draperi bronzi",
    "code": "COD. 10 492/19",
    "price": 128.9,
    "dims": "Lartësia 15 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-702_18",
    "categoryId": "llampa",
    "name": "Llambë moderne e zezë",
    "code": "COD. 10 702/18",
    "price": 135.9,
    "dims": "Lartësia 18 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-10-705_18",
    "categoryId": "llampa",
    "name": "Llambë me degë gjethe",
    "code": "COD. 10 705/18",
    "price": 135.9,
    "dims": "Lartësia 18 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-11-163_33",
    "categoryId": "llampa",
    "name": "Llambë fener e gjatë",
    "code": "COD. 11 163/33",
    "price": 173.9,
    "dims": "Lartësia 34 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "llampa-11-786_24",
    "categoryId": "llampa",
    "name": "Llambë klasike kupolë",
    "code": "COD. 11 786/24",
    "price": 137.9,
    "dims": "Lartësia 19 cm",
    "mat": "Bronz 87 + qelq muranese",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-303_06",
    "categoryId": "ndricim",
    "name": "Trëndafil i kuq me dritë",
    "code": "COD. 13 303/06",
    "price": 108.9,
    "dims": "cm 17 × 7,53",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-308_06",
    "categoryId": "ndricim",
    "name": "Trëndafil blu me dritë",
    "code": "COD. 13 308/06",
    "price": 108.9,
    "dims": "cm 17 × 7,53",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-327_06",
    "categoryId": "ndricim",
    "name": "Zemër e artë me dritë",
    "code": "COD. 13 327/06",
    "price": 108.9,
    "dims": "cm 17 × 7,5",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-333_06",
    "categoryId": "ndricim",
    "name": "Zemër e bardhë me dritë",
    "code": "COD. 13 333/06",
    "price": 108.9,
    "dims": "cm 17 × 7,5",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-176_03",
    "categoryId": "ndricim",
    "name": "Kristal oval me trëndafil",
    "code": "COD. 13 176/03",
    "price": 99.9,
    "dims": "cm 13",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-102_06",
    "categoryId": "ndricim",
    "name": "Kristal me pëllumb",
    "code": "COD. 13 102/06",
    "price": 96.9,
    "dims": "cm 12 × 13",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-169_03",
    "categoryId": "ndricim",
    "name": "Kristal me lule",
    "code": "COD. 13 169/03",
    "price": 99.9,
    "dims": "cm 13",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "ndricim-13-310_06",
    "categoryId": "ndricim",
    "name": "Trëndafil rozë me dritë",
    "code": "COD. 13 310/06",
    "price": 108.9,
    "dims": "cm 17 × 7,53",
    "mat": "Porselan Capodimonte / Kristal",
    "img": "/images/categories/ndricim.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-010_10",
    "categoryId": "korniza",
    "name": "Kornizë drejtkëndore klasike",
    "code": "COD. 21 010/10",
    "price": 50.9,
    "dims": "cm 10 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-19-002_11",
    "categoryId": "korniza",
    "name": "Kornizë ovale e artë",
    "code": "COD. 19 002/11",
    "price": 52.9,
    "dims": "cm 11 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-19-820_11",
    "categoryId": "korniza",
    "name": "Kornizë ovale Baroke",
    "code": "COD. 19 820/11",
    "price": 52.9,
    "dims": "cm 11 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-005_11",
    "categoryId": "korniza",
    "name": "Kornizë moderne e errët",
    "code": "COD. 21 005/11",
    "price": 52.9,
    "dims": "cm 11 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-035_11",
    "categoryId": "korniza",
    "name": "Kornizë e rrumbullakët e artë",
    "code": "COD. 21 035/11",
    "price": 52.9,
    "dims": "cm 11 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-564_10",
    "categoryId": "korniza",
    "name": "Kornizë moderne me gjethe",
    "code": "COD. 21 564/10",
    "price": 50.9,
    "dims": "cm 10 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-473_10",
    "categoryId": "korniza",
    "name": "Kornizë klasike e artë",
    "code": "COD. 21 473/10",
    "price": 50.9,
    "dims": "cm 10 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-19-045_11",
    "categoryId": "korniza",
    "name": "Kornizë ovale “Terra Antica”",
    "code": "COD. 19 045/11",
    "price": 52.9,
    "dims": "cm 11 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-212_08",
    "categoryId": "korniza",
    "name": "Kornizë e artë minimaliste",
    "code": "COD. 21 212/08",
    "price": 44.9,
    "dims": "cm 8 × 10",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-19-823_09",
    "categoryId": "korniza",
    "name": "Kornizë ovale e vogël",
    "code": "COD. 19 823/09",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-19-715_08",
    "categoryId": "korniza",
    "name": "Kornizë klasike me dekor",
    "code": "COD. 19 715/08",
    "price": 44.9,
    "dims": "cm 8 × 10",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "korniza-21-542_10",
    "categoryId": "korniza",
    "name": "Kornizë ovale vintage",
    "code": "COD. 21 542/10",
    "price": 50.9,
    "dims": "cm 10 × 15",
    "mat": "Bronz 87 — patinë artistike",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-674_14",
    "categoryId": "targa",
    "name": "Kornizë tavoline e artë",
    "code": "COD. 32 674/14",
    "price": 164.9,
    "dims": "cm 14 × 8",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-31-178_15",
    "categoryId": "targa",
    "name": "Bazoreliev — Duart e Madonnës",
    "code": "COD. 31 178/15",
    "price": 172.9,
    "dims": "cm 15 × 8,5",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-31-115_16",
    "categoryId": "targa",
    "name": "Bazoreliev — Madonna ovale",
    "code": "COD. 31 115/16",
    "price": 181.9,
    "dims": "cm 16 × 13",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-578_105",
    "categoryId": "targa",
    "name": "Targë me kurorë gjethi",
    "code": "COD. 32 578/105",
    "price": 138.9,
    "dims": "cm 11 × 8,5",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-055_30",
    "categoryId": "targa",
    "name": "Bazoreliev — Krishti",
    "code": "COD. 32 055/30",
    "price": 300.9,
    "dims": "cm 30 × 26",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-099_54",
    "categoryId": "targa",
    "name": "Targë libër e hapur",
    "code": "COD. 32 099/54",
    "price": 504.9,
    "dims": "cm 54 × 26",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-995_51",
    "categoryId": "targa",
    "name": "Pergamenë me pëllumb",
    "code": "COD. 32 995/51",
    "price": 478.9,
    "dims": "cm 51 × 39",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-31-349_41",
    "categoryId": "targa",
    "name": "Targë me kurorë dafine",
    "code": "COD. 31 349/41",
    "price": 393.9,
    "dims": "cm 41 × 18,5",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-31-680_36",
    "categoryId": "targa",
    "name": "Pergamenë e artë",
    "code": "COD. 31 680/36",
    "price": 351.9,
    "dims": "cm 36 × 52,53",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-470_35",
    "categoryId": "targa",
    "name": "Targë me shirit",
    "code": "COD. 32 470/35",
    "price": 342.9,
    "dims": "cm 35 × 37",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-32-421_31",
    "categoryId": "targa",
    "name": "Bazoreliev — Pietà",
    "code": "COD. 32 421/31",
    "price": 308.9,
    "dims": "cm 31 × 47",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "targa-31-040_17",
    "categoryId": "targa",
    "name": "Bazoreliev — Frymëzim",
    "code": "COD. 31 040/17",
    "price": 189.9,
    "dims": "cm 17 × 11",
    "mat": "Bronz 87 me finitim të thellë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-91",
    "categoryId": "targa",
    "name": "Bazoreliev — Pietà me Krishtin",
    "code": "",
    "price": 395.9,
    "dims": "",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-92",
    "categoryId": "targa",
    "name": "Bazoreliev — Engjëll i ulur",
    "code": "",
    "price": 395.9,
    "dims": "",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-94",
    "categoryId": "vazo",
    "name": "Urnë moderne e zezë",
    "code": "",
    "price": 271.9,
    "dims": "Lartësia 21 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-95",
    "categoryId": "vazo",
    "name": "Urnë kub e bardhë",
    "code": "",
    "price": 271.9,
    "dims": "Lartësia 21 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-96",
    "categoryId": "vazo",
    "name": "Urnë kub blu",
    "code": "",
    "price": 271.9,
    "dims": "Lartësia 21 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-97",
    "categoryId": "vazo",
    "name": "Urnë kub me lule",
    "code": "",
    "price": 271.9,
    "dims": "Lartësia 21 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-98",
    "categoryId": "vazo",
    "name": "Urnë trëndafil blu",
    "code": "",
    "price": 206.9,
    "dims": "Lartësia 11 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "urna-99",
    "categoryId": "vazo",
    "name": "Urnë trëndafil rozë",
    "code": "",
    "price": 297.9,
    "dims": "Lartësia 25 cm",
    "mat": "Rezinë premium / Bronz",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-21-369_35",
    "categoryId": "vazo",
    "name": "Urnë trëndafil e kuqe",
    "code": "COD. 21 369/35",
    "price": 105.9,
    "dims": "cm 25 × 42,5",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-32-558_08",
    "categoryId": "vazo",
    "name": "Urnë e bardhë klasike",
    "code": "COD. 32 558/08",
    "price": 91.9,
    "dims": "cm 18",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-22-042_100",
    "categoryId": "vazo",
    "name": "Urnë klasike jeshile",
    "code": "COD. 22 042/100",
    "price": 89.9,
    "dims": "cm 17 × 10",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-22-013_100",
    "categoryId": "targa",
    "name": "Libër i artë me kornizë",
    "code": "COD. 22 013/100",
    "price": 89.9,
    "dims": "cm 17 × 10",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-33-001_10",
    "categoryId": "targa",
    "name": "Zemër e artë",
    "code": "COD. 33 001/10",
    "price": 75.9,
    "dims": "cm 10",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-105",
    "categoryId": "targa",
    "name": "Pergamenë e artë me shirit",
    "code": "",
    "price": 135.9,
    "dims": "",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "libra-21-007_10",
    "categoryId": "targa",
    "name": "Pergamenë me jastëk",
    "code": "COD. 21 007/10",
    "price": 73.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 me finish të artë",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-290_46",
    "categoryId": "targa",
    "name": "Zemër me gdhendje",
    "code": "COD. 34 290/46",
    "price": 167.9,
    "dims": "Lartësia 45 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-330_45",
    "categoryId": "targa",
    "name": "Pergamenë “I Tuoi Cari”",
    "code": "COD. 34 330/45",
    "price": 167.9,
    "dims": "Lartësia 45 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-350_45",
    "categoryId": "targa",
    "name": "Kornizë e artë drejtkëndore",
    "code": "COD. 34 350/45",
    "price": 167.9,
    "dims": "Lartësia 45 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-250_52",
    "categoryId": "mozaik",
    "name": "Mozaike — Iris blu",
    "code": "COD. 34 250/52",
    "price": 178.9,
    "dims": "Lartësia 52 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-270_41",
    "categoryId": "mozaik",
    "name": "Mozaike — Zambakë blu",
    "code": "COD. 34 270/41",
    "price": 160.9,
    "dims": "Lartësia 41 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-200_37",
    "categoryId": "mozaik",
    "name": "Mozaike — Trëndafinj të kuq",
    "code": "COD. 34 200/37",
    "price": 154.9,
    "dims": "Lartësia 37 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "mozaik-34-230_51",
    "categoryId": "mozaik",
    "name": "Mozaike — Trëndafil i kuq",
    "code": "COD. 34 230/51",
    "price": 176.9,
    "dims": "Lartësia 51 cm",
    "mat": "Mozaik qelqi + bronz 87",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-23-005_20",
    "categoryId": "kryqe",
    "name": "Mozaike — Kryq diellor",
    "code": "COD. 23 005/20",
    "price": 77.9,
    "dims": "cm 14 × 7",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-19-002_11",
    "categoryId": "mozaik",
    "name": "Mozaike — Zemër me trëndafil",
    "code": "COD. 19 002/11",
    "price": 88.9,
    "dims": "cm 19 × 12",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-23-010_20",
    "categoryId": "mozaik",
    "name": "Mozaike — Kaliopë blu",
    "code": "COD. 23 010/20",
    "price": 77.9,
    "dims": "cm 14 × 7",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/mozaik.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-21-012_10",
    "categoryId": "kryqe",
    "name": "Kryq i artë 24kt",
    "code": "COD. 21 012/10",
    "price": 68.9,
    "dims": "cm 10 × 15",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-19-005_11",
    "categoryId": "korniza",
    "name": "Kornizë ovale e artë 24kt",
    "code": "COD. 19 005/11",
    "price": 66.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-21-025_10",
    "categoryId": "kryqe",
    "name": "Kryq modern i artë 24kt",
    "code": "COD. 21 025/10",
    "price": 66.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "preziosi-19-014_11",
    "categoryId": "korniza",
    "name": "Kornizë katrore e artë 24kt",
    "code": "COD. 19 014/11",
    "price": 88.9,
    "dims": "cm 19 × 12",
    "mat": "Bronz 87 i veshur me ar 24kt",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-19-021_09",
    "categoryId": "korniza",
    "name": "Kornizë ovale klasike 24kt",
    "code": "COD. 19 021/09",
    "price": 51.9,
    "dims": "cm 8 × 10",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-065_20",
    "categoryId": "korniza",
    "name": "Kornizë drejtkëndore e artë 24kt",
    "code": "COD. 10 065/20",
    "price": 161.9,
    "dims": "cm 20 × 12212",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-101_20",
    "categoryId": "korniza",
    "name": "Kornizë ovale antike 24kt",
    "code": "COD. 10 101/20",
    "price": 161.9,
    "dims": "cm 20 × 12212",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-135_20",
    "categoryId": "korniza",
    "name": "Kornizë ovale klasike",
    "code": "COD. 10 135/20",
    "price": 161.9,
    "dims": "cm 20 × 12212",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-24-510_20",
    "categoryId": "llampa",
    "name": "Llambë qiriu me qelq të kuq",
    "code": "COD. 24 510/20",
    "price": 53.9,
    "dims": "cm 15 × 6",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-21-034_10",
    "categoryId": "llampa",
    "name": "Llambë e gjelbër klasike",
    "code": "COD. 21 034/10",
    "price": 54.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-180_19",
    "categoryId": "llampa",
    "name": "Llambë qelqi qelibar",
    "code": "COD. 10 180/19",
    "price": 158.9,
    "dims": "cm 19 × 14,53",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-220_19",
    "categoryId": "kryqe",
    "name": "Kryq modern bronzi",
    "code": "COD. 10 220/19",
    "price": 174.9,
    "dims": "cm 25 × 14",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-220_19-b",
    "categoryId": "korniza",
    "name": "Kornizë tavoline me bazë",
    "code": "COD. 10 220/19",
    "price": 158.9,
    "dims": "cm 19 × 14,53",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-316_18",
    "categoryId": "llampa",
    "name": "Llambë klasike e gjelbër",
    "code": "COD. 10 316/18",
    "price": 155.9,
    "dims": "cm 18 × 14212,5",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-31-688_14",
    "categoryId": "llampa",
    "name": "Llambë me shirit bronzi",
    "code": "COD. 31 688/14",
    "price": 90.9,
    "dims": "cm 14 × 12,5",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-31-661_13",
    "categoryId": "kryqe",
    "name": "Kryqëzim klasik",
    "code": "COD. 31 661/13",
    "price": 87.9,
    "dims": "cm 13 × 10",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-23-316_20",
    "categoryId": "llampa",
    "name": "Llambë e artë me qelq",
    "code": "COD. 23 316/20",
    "price": 53.9,
    "dims": "cm 15 × 7,5",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "shell-10-933_18",
    "categoryId": "llampa",
    "name": "Llambë e errët me qelq",
    "code": "COD. 10 933/18",
    "price": 155.9,
    "dims": "cm 18 × 14212,5",
    "mat": "Bronz 87 (Shell Moulding)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-50-081_395",
    "categoryId": "kryqe",
    "name": "Kryq i thjeshtë bronzi",
    "code": "COD. 50 081/395",
    "price": 93.9,
    "dims": "",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-21-021_11",
    "categoryId": "kryqe",
    "name": "Kryq i artë modern",
    "code": "COD. 21 021/11",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-10-029_23",
    "categoryId": "llampa",
    "name": "Llambë bronzi me rreze",
    "code": "COD. 10 029/23",
    "price": 116.9,
    "dims": "cm 10 × 16",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/llampa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-21-061_10",
    "categoryId": "korniza",
    "name": "Kornizë ovale e artë",
    "code": "COD. 21 061/10",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-19-001_11",
    "categoryId": "targa",
    "name": "Fregio — Gjeth e artë",
    "code": "COD. 19 001/11",
    "price": 60.9,
    "dims": "cm 14 × 637,5",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-21-071_10",
    "categoryId": "targa",
    "name": "Fregio — Kalk i artë",
    "code": "COD. 21 071/10",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/targa.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-19-057_11",
    "categoryId": "korniza",
    "name": "Kornizë jeshile moderne",
    "code": "COD. 19 057/11",
    "price": 60.9,
    "dims": "cm 14 × 637,5",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-19-073_11",
    "categoryId": "vazo",
    "name": "Vazë bronzi moderne",
    "code": "COD. 19 073/11",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-19-892_11",
    "categoryId": "korniza",
    "name": "Kornizë e artë moderne",
    "code": "COD. 19 892/11",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-21-651_10",
    "categoryId": "vazo",
    "name": "Vazë tulipan rozë",
    "code": "COD. 21 651/10",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-11-904_17",
    "categoryId": "korniza",
    "name": "Kornizë rrethore blu",
    "code": "COD. 11 904/17",
    "price": 132.9,
    "dims": "cm 17 × 12211,5",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-10-695_18",
    "categoryId": "kryqe",
    "name": "Kryq modern jeshil",
    "code": "COD. 10 695/18",
    "price": 135.9,
    "dims": "cm 18 × 11,53",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-21-451_10",
    "categoryId": "vazo",
    "name": "Vazë tulipan jeshile",
    "code": "COD. 21 451/10",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/vazo.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-19-660_11",
    "categoryId": "kryqe",
    "name": "Kryq modern i kuq",
    "code": "COD. 19 660/11",
    "price": 47.9,
    "dims": "cm 9 × 12",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-10-090_12",
    "categoryId": "kryqe",
    "name": "Kryq modern jeshil",
    "code": "COD. 10 090/12",
    "price": 118.9,
    "dims": "cm 11 × 9,53",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/kryqe.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-10-090_20",
    "categoryId": "korniza",
    "name": "Kornizë rrethore jeshile",
    "code": "COD. 10 090/20",
    "price": 137.9,
    "dims": "cm 19 × 11213",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-158",
    "categoryId": "korniza",
    "name": "Kornizë e artë rrethore",
    "code": "",
    "price": 105.9,
    "dims": "cm 30 × 17149",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  },
  {
    "id": "seri-10-040_20",
    "categoryId": "korniza",
    "name": "Kornizë ovale e artë moderne",
    "code": "COD. 10 040/20",
    "price": 137.9,
    "dims": "cm 19 × 12212",
    "mat": "Bronz 87 i pressuar (Pressofusione)",
    "img": "/images/categories/korniza.jpg",
    "featured": false,
    "featuredOrder": 0
  }
];
